name: projet_python
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.3
  - numpy=1.26.4
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - plotly=5.24.1
  - streamlit=1.41.1
  - jupyter=1.1.1
  - notebook=7.3.2
  - pytest=7.4.4
  - dask=2024.8.2
  - requests=2.32.3
  - python-dateutil=2.9.0
  - pytz=2024.1
